Class {
	#name : #SVGBaseline,
	#superclass : #SVGEnumerationType,
	#category : #'SeasideDynamicSVG-Core'
}

{ #category : #accessing }
SVGBaseline class >> alphabetic [

	^ 'alphabetic'
]

{ #category : #accessing }
SVGBaseline class >> baseline [

	^ 'baseline'
]

{ #category : #accessing }
SVGBaseline class >> central [

	^ 'central'
]

{ #category : #accessing }
SVGBaseline class >> hanging [

	^ 'hanging'
]

{ #category : #accessing }
SVGBaseline class >> ideographic [

	 ^ 'ideographic'
]

{ #category : #accessing }
SVGBaseline class >> mathematical [

	^ 'mathematical'
]

{ #category : #accessing }
SVGBaseline class >> middle [

	^ 'middle'
]

{ #category : #accessing }
SVGBaseline class >> textAfterEdge [

	^ 'text-after-edge'
]

{ #category : #accessing }
SVGBaseline class >> textBeforeEdge [

	^ 'text-before-edge'
]
