Class {
	#name : #SVGBaseline,
	#superclass : #SVGEnumeration,
	#category : #'SeasideDynamicSVG-Core-Enumerations'
}

{ #category : #'alignment only' }
SVGBaseline class >> afterEdge [

	^ 'after-edge'
]

{ #category : #accessing }
SVGBaseline class >> alphabetic [

	^ 'alphabetic'
]

{ #category : #accessing }
SVGBaseline class >> baseline [

	^ 'baseline'
]

{ #category : #'alignment only' }
SVGBaseline class >> beforeEdge [

	^ 'before-edge'
]

{ #category : #accessing }
SVGBaseline class >> central [

	^ 'central'
]

{ #category : #accessing }
SVGBaseline class >> hanging [

	^ 'hanging'
]

{ #category : #accessing }
SVGBaseline class >> ideographic [

	 ^ 'ideographic'
]

{ #category : #accessing }
SVGBaseline class >> mathematical [

	^ 'mathematical'
]

{ #category : #accessing }
SVGBaseline class >> middle [

	^ 'middle'
]

{ #category : #'dominant baseline only' }
SVGBaseline class >> noChange [

	 ^ 'no-change'
]

{ #category : #'dominant baseline only' }
SVGBaseline class >> resetSize [

	 ^ 'reset-size'
]

{ #category : #accessing }
SVGBaseline class >> textAfterEdge [

	^ 'text-after-edge'
]

{ #category : #accessing }
SVGBaseline class >> textBeforeEdge [

	^ 'text-before-edge'
]

{ #category : #'dominant baseline only' }
SVGBaseline class >> useScript [

	 ^ 'use-script'
]
