Class {
	#name : #SVGCoordinateSystem,
	#superclass : #SVGEnumeration,
	#category : #'SeasideDynamicSVG-Core-Enumerations'
}

{ #category : #accessing }
SVGCoordinateSystem class >> objectBoundingBox [

	^ 'objectBoundingBox'
]

{ #category : #shapes }
SVGCoordinateSystem class >> strokeWidth [ 

	^ 'strokeWidth'
]

{ #category : #accessing }
SVGCoordinateSystem class >> userSpaceOnUse [

	^ 'userSpaceOnUse'
]
