Class {
	#name : #SVGAspectRatio,
	#superclass : #SVGEnumeration,
	#category : #'SeasideDynamicSVG-Core-Enumerations'
}

{ #category : #accessing }
SVGAspectRatio class >> none [

	^ 'none'
]

{ #category : #accessing }
SVGAspectRatio class >> xMaxYMax [       

	^ 'xMaxYMax'
]

{ #category : #accessing }
SVGAspectRatio class >> xMaxYMid [    

	^ 'xMaxYMid'
]

{ #category : #accessing }
SVGAspectRatio class >> xMaxYMin [ 

	^ 'xMaxYMin'
]

{ #category : #accessing }
SVGAspectRatio class >> xMidYMax [      

	^ 'xMidYMax'
]

{ #category : #accessing }
SVGAspectRatio class >> xMidYMid [   

	^ 'xMidYMid'
]

{ #category : #accessing }
SVGAspectRatio class >> xMidYMin [ 

	^ 'xMidYMin'
]

{ #category : #accessing }
SVGAspectRatio class >> xMinYMax [     

	^ 'xMinYMax'
]

{ #category : #accessing }
SVGAspectRatio class >> xMinYMid [  

	^ 'xMinYMid'
]

{ #category : #accessing }
SVGAspectRatio class >> xMinYMin [

	^ 'xMinYMin'
]
