Class {
	#name : #SVGDisabledAnchorBrush,
	#superclass : #SVGAnchorTag,
	#category : #'SeasideDynamicSVG-Core-Base'
}

{ #category : #callbacks }
SVGDisabledAnchorBrush >> callback: aBlock [
	" ignored "
	
	
]

{ #category : #private }
SVGDisabledAnchorBrush >> closeTag [
	" disabled! "
	
	
]

{ #category : #testing }
SVGDisabledAnchorBrush >> isClosed [
	
	^true
]

{ #category : #callbacks }
SVGDisabledAnchorBrush >> on: aSymbol of: anObject [
	" ignored "
	
	
]

{ #category : #private }
SVGDisabledAnchorBrush >> openTag [
	" disabled! "
	
	
]
