Class {
	#name : #SVGUserAgentAdaptor,
	#superclass : #Object,
	#category : #'SeasideDynamicSVG-Core-Base'
}

{ #category : #'browser specific' }
SVGUserAgentAdaptor >> fullTagForInlinedSVGTag: tag [

	^ tag
]

{ #category : #'browser specific' }
SVGUserAgentAdaptor >> prepareResponseForInlinedSVG: aResponse [


]

{ #category : #'browser specific' }
SVGUserAgentAdaptor >> renderPreambleForInlinedSVGOn: canvas [ 
	
]

{ #category : #'browser specific' }
SVGUserAgentAdaptor >> updateRoot: aHtmlRoot [
]
